name: flutter_login
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  get_version: ^0.0.8+5
  flutter_whatsnew: ^1.0.3
  shared_preferences: ^2.0.6
  local_auth: ^1.1.6
  cupertino_icons: ^1.0.3
  persist_theme: ^1.7.0
  http: ^0.13.3
  json_annotation: ^4.1.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - CHANGELOG.md
