name: truth_or_dare
description: Truth or dare application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  google_fonts: ^2.1.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  image_path: "assets/images/icon_128x128.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/fonts/Nunito/
