import 'dart:math';

abstract class TruthOrDareGenerator {
  String getQuestion();
  String getDare();
}

class TruthOrDareLocalGenerator implements TruthOrDareGenerator {
  final Random _random = Random();
  final _questions = [
    "En son söylediğin yalan nedir?",
    "Bir randevuda yaptığın en utanç verici şey neydi?",
    "Arabanızla hiç kazara bir şeye (ya da birine!) çarptınız mı?",
    "Seviyormuş gibi yaptığın ama aslında dayanamadığın birinin adını söyle.",
    "En tuhaf takma adınız nedir?",
    "Fiziksel olarak en acı verici deneyiminiz neydi?",
    "Hangi köprüleri yaktığın için mutlusun?",
    "Toplu taşımada yaptığınız en çılgın şey nedir?",
    "Bir cinle tanışsaydın üç dileğin ne olurdu?",
    "Amerika Birleşik Devletleri Başkanlığı için dünyadaki herhangi birini yazabilseydiniz, bu kim olurdu ve neden?",
    "Başka birine söylediğin en kötü şey nedir?",
    "En kötü öpücüğün kimdi?",
    "Sonucu olmayacağını bilseydin yapacağın bir şey ne olurdu?",
    "Aynanın karşısında yaptığınız en çılgınca şey nedir?",
    "Başkası hakkında söylediğin en kötü şey nedir?",
    "Partnerinizin önünde asla yapmayacağınız, arkadaşlarınızla yapmayı sevdiğiniz şey nedir?",
    "En çok kimi kıskanıyorsun?",
    "Favori pijamalarınız neye benziyor?",
    "Hiç bir partiden çıkmak için hasta numarası yaptın mı?",
    "Çıktığın en yaşlı kişi kim?",
    "Günde kaç tane selfie çekiyorsun?",
    "Meatloaf aşk için her şeyi yapacağını söylüyor ama “bunu” yapmıyor. Senin o nedir?",
    "Aynı pantolonu haftada kaç kez giyiyorsunuz?",
    "Bugün lise aşkınla çıkar mısın?",
    "nerelerde gıdıklanıyorsun",
    "Herhangi bir batıl inanca inanıyor musunuz? Öyleyse hangileri?",
    "Beğendiğini itiraf etmekten utandığın bir film hangisi?",
    "En utanç verici bakım alışkanlığınız nedir?",
    "En son ne zaman özür diledin? Ne için?",
    "Alacakaranlık efsanesi hakkında gerçekten nasılsınsun?",
    "Utanç verici kokularınızın çoğu nereden geliyor?",
    "Hiç bir partneri aldatmayı düşündün mü?",
    "Hiç bir partneri aldattın mı?",
    "Boksörler mi, külotlar mı?",
    "Hiç havuza işedin mi?",
    "Şimdiye kadar saç yetiştirdiğiniz en tuhaf yer neresiydi?",
    "Asla yakalanmayacağınız garanti edilseydi, Dünya'da kimi öldürürdünüz?",
    "Başkası için aldığınız en ucuz hediye nedir?",
    "En çok hangi uygulamada zaman harcıyorsunuz?",
    "Uçakta yaptığınız en tuhaf şey nedir?",
    "Hiç toplum içinde çıplak kaldınız mı?",
    "Günde kaç tane dedikodu blogu okuyorsun?",
    "Çıkacağın en küçük yaştaki partnerin kim?",
    "Hiç toplum içinde burnunuzu karıştırdınız mı?",
    "Yaşınız hakkında hiç yalan söylediniz mi?",
    "Telefonunuzdan bir uygulamayı silmek zorunda kalsaydınız, bu hangisi olurdu?",
    "En utanç verici gece geç saatlerde satın aldığınız şey nedir?",
    "Duş almadan en uzun süre ne kadar kaldınız?",
    "Hiç sahte kimlik kullandınız mı?",
    "Koridor geçişin kim?",
    "Dürüst olun: Favori bir çocuğunuz var mı?",
    "Ailenizden en çok hangisi sizi rahatsız ediyor ve neden?",
    "Bir ilişkide en büyük korkunuz nedir?",
    "Solunuzdaki kişiyle ilgili en büyük evcil hayvan çileniz nedir?",
    "Şu anda telefonunuzdaki en utanç verici metin nedir?",
    "Hiç ceset gördün mü?",
    "Sizce hangi ünlü abartılıyor?",
    "Patronunuza hiç yalan söylediniz mi?",
    "Hiç işten bir şey çaldın mı?",
    "Dişlerinizi fırçalamadan en uzun süre ne kadar kaldınız?",
    "Hayattaki en büyük pişmanlığın nedir?",
    "Kimi çıplak görmekten nefret edersin?",
    "Sarhoşken yaptığınız en tuhaf şeyi anlatın.",
    "Hiç hediye aldın mı?",
    "1 milyon için sevgilinizden ayrılır mısınız?",
    "Hiç bir iş arkadaşınıza aşık oldunuz mu?",
    "Eski sevgililerinden herhangi birine karşı hala hislerin var mı?",
    "Bir restoranda bıraktığın en küçük bahşiş nedir?",
    "Hiç aşık olduğunuz veya partnerinizin dikkatini çekmek için yaptığınız bir şeyden pişman oldunuz mu?",
    "Asla yapmayacağın bir iş nedir?",
    "Hiç bir arkadaşınızı hayaletlediniz mi?",
    "Hiç bir ortağı hayal ettin mi?",
    "Bulutunuzdaki en skandal fotoğraf hangisi?",
    "Bir günlüğüne cinsiyet değiştirsen ne yapardın?",
    "Telefonunuzda kaç tane fotoğraf düzenleme uygulaması var?",
    "Kaç çift büyükanne külotun var?",
    "Vücudunuzdan en sevdiğiniz ve en sevmediğiniz yerler hangileri?",
    "En son ne zaman terk edildin?",
    "Hâlâ yaptığınız en çocukça şey nedir?",
    "En son ne zaman birini terk ettin?",
    "Bir yarışma programında partneriniz olarak bu odadan birini seçecek olsaydınız bu kim olurdu ve neden?",
    "Kendinden kısa biriyle çıkarmısın",
    "Hiç bir arkadaşın için yalan söyledin mi?",
    "Bu odadaki her insan hakkında değiştireceğiniz bir şey söyleyin.",
    "En son ne zaman başka birini ağlattın?",
    "Kalabalığın önünde yaptığınız en utanç verici şey nedir?",
    "Görünmez olabilseydin, yapacağın en kötü şey ne olurdu?",
    "Bir parça yiyeceği düşürdükten sonra, yemeden önce en uzun süre yerde ne kadar süre bıraktınız?",
    "Hayatında değiştirmek istediğin bir şey var mı?",
    "Aynı anda iki kişiyle çıkabilseydin, yapar mıydın? Eğer öyleyse, kim?",
    "Seni bunaltan şey nedir?",
    "Hayatının en büyük günü neydi?",
    "Yine de öğrenmek isteyeceğin işe yaramaz bir beceri nedir?",
    "Dolaplarınızı gözden geçirseydim, bulacağım en tuhaf şey ne olurdu?",
    "Hiç osurdun ve suçu başkasına attın mı?",
    "İşyerinde yaptığın en kötü şey nedir?",
    "kaç kişiyle öpüştün",
    "Numaran kaç?",
    "Hiç hoş olmayan bir fotoğrafını paylaştığın için bir arkadaşına kızdın mı?",
    "En saçma anlaşma kırıcınız nedir?"
  ];

  final _dares = [
    "100 squat yap.",
    "Telefonunuzda en utanç verici fotoğrafı gösterin.",
    "Sağınızdaki kişiye ayak masajı yapın.",
    "Solunuzdaki kişiye kötü bir şey söyleyin.",
    "Grubun geri kalanının Instagram hesabınızdan birisine DM atmasına izin verin.",
    "Ellerinizi kullanmadan bir muz yiyin.",
    "Bir dakika twerk.",
    "Tekrar gidene kadar gözlerini kapalı tut.",
    "Facebook haber akışınızdaki ilk 15 gönderiyi beğenin.",
    "Telefon rehberinizdeki son kişiye seks mesajı gönderin.",
    "Çiğ soğan ye.",
    "Üç buz küpünü eriyene kadar ağzınızda tutun.",
    "Seçtiğiniz birine kucak dansı yapın.",
    "Aklına gelen ilk kelimeyi söyle.",
    "Orgazm yüzünü göster.",
    "Cüzdanını/çantanı boşalt ve herkese içinde ne olduğunu göster.",
    "Mesaj attığın son beş kişiyi ve mesajların ne dediğini göster.",
    "Tüm yumruğunu ağzına sokmaya çalış.",
    "Dört giysiyi çıkarın.",
    "Bir kaşık hardal ye.",
    "Bir bardağa 10 farklı sıvı koyun ve için.",
    "Doğmuş bir bebekle ilgili en iyi izleniminizi yapın.",
    "Dirseğinizi yalamaya çalışın.",
    "10 dakika boyunca sağınızdaki kişi gibi davranın.",
    "Önümüzdeki 5 dakika boyunca birinin evcil hayvanı olun.",
    "Bir bardak suyu ellerinin üzerinde durarak içmeye çalış.",
    "En iyi seksi taramanı yap.",
    "Gruptaki herkes hakkında iki dürüst şey söyle.",
    "Ağzınıza mümkün olduğu kadar çok atıştırmalık koyun.",
    "Grubu olabildiğince çabuk güldürmeye çalışın.",
    "Vücudunuzun bir bölümünü tıraş edin.",
    "Herkese kendin hakkında utanç verici bir hikaye anlat.",
    "Telefonunuzdaki en eski özçekimi Instagram Stories'de yayınlayın.",
    "Erkek için makyaj yap. Bir kız için makyajını yıka.",
    "Sırayla dört çember yapın.",
    "Bildiğin en üzücü hikayeyi anlat.",
    "Hayatın buna bağlıymış gibi göbek dansı.",
    "Denizci gibi 20 saniye boyunca lanet olsun.",
    "Kurt gibi uluyun.",
    "Bir dakika müziksiz dans et.",
    "Hayali bir direkle direk dansı.",
    "Başkasının seni gıdıklamasına ve gülmemeye çalışmasına izin ver.",
    "Sağınızdaki kişiye serenat yapın.",
    "Önümüzdeki 3 tur için aksanlı konuşun.",
    "Gruptaki herkesi gülümsetin, herkes bir gülümseme kırana kadar devam edin.",
    "Solunuzdaki kişiyi öpün.",
    "Bir sihir numarası yapmaya çalışın.",
    "Beş yemek kaşığı baharat ye.",
    "Bir dakika boyunca dans etmeye çalış.",
    "Grubun sana yeni bir saç modeli vermesine izin ver.",
    "Solucan yap.",
    "Kıyafetlerinle duş al.",
    "Kafana iki yumurta kır.",
    "En iyi satıcılığınızı kullanarak gruptaki birine bir parça çöp sat.",
    "Mümkün olduğunca ellerinizin üzerinde yürümeye çalışın.",
    "Her konuştuğunuzda bir ünlüyü taklit edin.",
    "Grubun seçtiği 2 veya 3 öğeyi hokkabazlık etmeye çalışın.",
    "Gargara yapılmaması gereken bir şeyi gargara yapın, ama size zarar vermez.",
    "Seçtiğiniz kişi tarafından yüzüne tokat olsun.",
    "Turun geri kalanı için belinizin etrafında hayali bir hula hoop döndürün.",
    "Gruptaki aynı cinsiyetten bir üyeyi baştan çıkarın.",
    "Grubun ortaya çıkardığı bir şeye dayanarak yerinde bir şiir oluşturun.",
    "Anket hayali bir kutupla 1 dakika dans et.",
    "Size bir şaplak vermek için gruptan birini seçin.",
    "Seçtiğiniz sosyal medya çıkışına kendinizin son derece çirkin bir resmini gönderin.",
    "Turun geri kalanı için komik bir surat tut.",
    "Odanda bir şey hayal et. Şimdi burnunuzla heceleyin ve gruptan biri ne hecelemeye çalıştığınızı tahmin edene kadar burnunuzla hecelemeye devam edin.",
    "Grup bir kaba kelime seçtikten sonra, bir şarkı söyleyin ve bu kaba kelimeyi şarkının her satırına bir kez ekleyin.",
    "Kıçınızı odanın bir ucundan diğerine bir köpek gibi halıya sürükleyin.",
    "Sadece ağzınızı kullanarak, ellerinizi veya ayaklarınızı kullanarak bir atıştırmalık veya şeker torbası açın.",
    "Belinizi bükün, böylece bacaklarınız arasında arkanıza bakıyorsunuz. Şimdi birini kıçınla etiketleyene kadar geriye doğru koş.",
    "Tuvalete git, iç çamaşırını çıkar ve kafana koy. Kafanın üzerinde oyun geri kalanı için giymek.",
    "Önümüzdeki 1 dakika boyunca birisinin bağırdığı herhangi bir hayvan gibi davranın.",
    "Mutfakta sahip olduğunuz en baharatlı şeyden bir çay kaşığı yiyin.",
    "Bir buz küpünü ağzınızdan sağınızdaki kişinin ağzına aktarın.",
    "Telefonunuzdaki 3. kişiyi arayın ve grubun söylediği şarkının 30 saniyesini söyleyin chooses.No konuşmak.",
    "Bir yemek gibi davran. Yemek yiyormuş gibi davranma, yemek yiyormuş gibi davran. Gruptaki biri ne tür bir yemek yediğinizi tahmin edene kadar rol yapmaya devam edin.",
    "Tuvalete bir şey bırak ve sonra almak için uzan.",
    "Adı, adınızla aynı harfe sahip olan veya adınızın ilk harfi sizinkine en yakın olan kişiyi bulun. Şimdi yüzlerini yala.",
    "Dönen bir sandalyeye oturun ve grubun sizi 30 saniye boyunca döndürmesini sağlayın.",
    "Tam bir dakika boyunca gidebildiğiniz kadar yukarı ve aşağı zıplayın.",
    "İki kişi aynı anda ıslak bir willy versin.",
    "Seçen gruplardan biri hakkında övgü dolu bir şarkı söyle.",
    "Yorumlayıcı dans yoluyla bir insan hayatını tasvir edin.",
    "1 dakika boyunca müziksiz dans edin.",
    "Kalıcı bir işaretleyici ile vücudunuzda bir yere utanç verici bir şey yazın (giysilerle gizlenebilir).",
    "Yalvarın ve sağınızdaki kişiye sizi başka bir erkek ya da kız için terk etmemesi için yalvarın.",
    "Pantolonunun altına buz küpleri koy.",
    "Kolunu dirseğinin yanındaki çöp kutusuna sok.",
    "Yeri yala.",
    "Üç tur için gruptaki karşı cinsten biriyle kıyafet değiştirin.",
    "Grubun sizi utanç verici bir pozisyonda pozlamasına ve fotoğraf çekmesine izin verin.",
    "Birine telefonunuzu verin ve kişilerinizdeki herkese bir metin göndermesine izin verin.",
    "Grubun bir dakika boyunca telefonunuza bakmasına izin verin.",
    "Grubun yaptığı küçük bir bardak suyu iç.",
    "Solunuzdaki kişinin yüzünüze bir kalemle çizmesine izin verin.",
    "Birisi taklit ettiğiniz videoyu tahmin edene kadar popüler YouTube videolarını taklit edin.",
    "Bir çöp tenekesi alın ve ellerinizle çöp tenekesinin üstünde bir çember yapın. Grubun diğer üyelerinin çemberinizden çöp atmaya çalışmasına izin verin.",
    "Gruptaki bir kişi veya insanlar hakkında 30 saniyelik bir opera yapın ve gerçekleştirin.",
    "Daha fazla yapamayana kadar şınav yapın, 5 saniye bekleyin ve sonra bir tane daha yapın."
  ];

  int _lastPickedQuestionNumber;

  @override
  String getQuestion() {
    int randomNumber = _random.nextInt(_questions.length);
    while (randomNumber == _lastPickedQuestionNumber) {
      randomNumber = _random.nextInt(_questions.length);
    }
    _lastPickedQuestionNumber = randomNumber;
    return _questions[randomNumber];
  }

  @override
  String getDare() {
    int randomNumber = _random.nextInt(_dares.length);
    while (randomNumber == _lastPickedQuestionNumber) {
      randomNumber = _random.nextInt(_dares.length);
    }
    _lastPickedQuestionNumber = randomNumber;
    return _dares[randomNumber];
  }
}
